### ISSUE TITLE
Not working on mac?

### ISSUE THREAD

**Issue by katopz** [takahirox/webgpu-devtools#2]
- macOS 10.15.7
- MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
- Intel Iris Plus Graphics 1536 MB
- Chrome Version 111.0.5563.110 (Official Build) (x86_64)

<img width="837" alt="image" src="https://user-images.githubusercontent.com/97060/227700983-34a2010d-786c-4064-8dc6-4208845d7ae8.png">

or I've to click some magic button first?

**Comment by takahirox** [comment]
From the URL in the URL bar, that page seems to use WebGL, not WebGPU.

**Comment by katopz** [comment]
Oh, just realized that! I thought it use same GPU pipeline output in the end (like GPU mem dump) which is not 😱 case close, sorry!

<img width="543" alt="image" src="https://user-images.githubusercontent.com/97060/227843878-3847b908-083d-495a-9b1d-d05e8d62cf05.png">
